version: "3.9"
services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes: 
      - cache:/data
    networks:
      - cn332
  scheduler:
    image: node:16
    working_dir: /app
    restart: always
    ports:
      - "3003:3003"
    volumes:
      - ".:/app/"
    command: sh -c "yarn && yarn build && yarn start:prod"
    environment:
      - TZ=Asia/Bangkok
    networks:
      - cn332
volumes:
  cache:
    driver: local
networks: 
  cn332: